### ISSUE TITLE
[error] [object Object] in class

### ISSUE THREAD

**Issue by derevandal** [potato4d/vue-fixed-header#106]
Hi, i've got an error when use `b-navbar` from bootstrap inside `fixed-header` component (v3.x).
It appears `[object Object]` inside component class.

HTML generated:
```html
<nav class="navbar [object Object] vue-fixed-header">
    lol
</nav>
```
CodeSandbox: https://codesandbox.io/s/ypyw43jj69?fontsize=14

I'm using v2.0.2 without error. 

Could you help me?

**Comment by potato4d** [comment]
@derevandal 
Thank you for the report. And I'm sorry.

`fixed.sync` is obsolete in v3.x.
Currently, this is determined by the existence of the `.vue-fixed-header--isFixed` class.
I have a problem with the documentation, so I will fix it.

**Comment by derevandal** [comment]
I understand... Is there some way to emit a event in component to watch
this on his parent?
Because I'm using `.sync` to make more customizations than toggle a class.

I read about `MutationObserver` in this post (
https://stackoverflow.com/questions/52779932/vue-watch-for-class-change)
but I think it's a feature that this component should have.

Thanks.

Em dom, 7 de abr de 2019 01:07, Takuma HANATANI <notifications@github.com>
escreveu:

**Comment by potato4d** [comment]
@derevandal 
If you want to detect a change, there is a change event.
Can you solve it using this?
https://vue-fixed-header.potato4d.dev/api/events.html#change

**Comment by derevandal** [comment]
Thanks man!
This solution is resolve my problem.
Thanks.
#closed

Em dom, 7 de abr de 2019 01:53, Takuma HANATANI <notifications@github.com>
escreveu:

**Comment by derevandal** [comment]
@potato4d I need reopen this issue...
When the first directly child is a components like `b-navbar`, `[object Object]` appears again.
```vue
  <FixedHeader>
      <b-navbar id="topbar" toggleable="lg" type="dark" fixed="top">
        <div>lol</div>
      </b-navbar>
  </FixedHeader>
```

When I use a div before b-nav, it works.
```vue
  <FixedHeader>
    <div>
      <b-navbar id="topbar" toggleable="lg" type="dark" fixed="top">
        <div>lol</div>
      </b-navbar>
    </div>
  </FixedHeader>
```

I thinks that something it's wrong with classes on merge.
SandBox: https://codesandbox.io/s/ypyw43jj69?fontsize=14
