### ISSUE TITLE
It's not working on iPhone XR

### ISSUE THREAD

**Issue by sliverdev009** [potato4d/vue-fixed-header#153]
Hi there,

I had integrated vue-fixed-header in my vue project. But it's not working on iPhone XR.
It's working for web browsers and old iPhone devices.

But it's not working as well on iPhone XR. Could  you check it and solve ASAP?

Best Regards.

**Comment by potato4d** [comment]
@cooldev93code 
Can you provide a minimal repository or codesandbox URL that can reproduce the problem?

**Comment by cooldev93code** [comment]
https://www.coralapp.co/yumthai

This is the website that I had integrated vue-fixed-header now. It's
working as well on the iPhone 7 / 8.
But fixed header is not working on the iPhone XR.

Also I have attached code to use vue-fixed-header in my project.

Please review it and give me feedback.

Thanks.

**Comment by jay8t6** [comment]
+1 not working on iphone 8 as well

**Comment by cooldev93code** [comment]
@potato4d  do you have any update? I want to solve this issue ASAP.

Best Regards.

**Comment by Apialos** [comment]
I had also a similar issue in some IOS devices. 
Tested in iOS, v11 Safari through browserstack, i find out that the class `vue-fixed-header--isFixed` is missing from the DOM when scrolled down.

**Comment by potato4d** [comment]
Is it fixed by iOS?
[![Image from Gyazo](https://i.gyazo.com/e8c70859d76df5882c40be1049503fa1.gif)](https://gyazo.com/e8c70859d76df5882c40be1049503fa1)

Please tell me if it reproduces.(I'll reopen this issue.)
