### ISSUE TITLE
why jsx

### ISSUE THREAD

**Issue by zvekov** [potato4d/vue-fixed-header#222]
I try not to use .jsx in development. In the last update I see the .jsx and the assembly breaks.
How to use now?
while I will use version 3.2.2

**Comment by potato4d** [comment]
The new build command is below and it works correctly.

```
~/.g/g/p/vue-fixed-header(master)> yarn tsc --build ./tsconfig.build.json
yarn run v1.15.2
$ /Users/potato4d/.ghq/github.com/potato4d/vue-fixed-header/node_modules/.bin/tsc --build ./tsconfig.build.json
✨  Done in 3.10s.
```
