### ISSUE TITLE
improving scroll handling and isFixed change detection

### ISSUE THREAD

**Issue by birdspider** [potato4d/vue-fixed-header#233]
Something is wrong around vue-fixed-header.ts#L55, somehow the last scoll event does not reset isFixed to false (unless I call `$refs.foo.check()` manually)

```
this.check = () => {
        const { threshold, hideScrollUp } = this
        let currentScrollPos = this.getScrollTop()
        this.isFixed =
          currentScrollPos >= this.lastScrollTop
            ? currentScrollPos > threshold
            : !hideScrollUp
        this.lastScrollTop = currentScrollPos
        this.$emit('change', this.isFixed)
        this.$forceUpdate()
      }
```

my fix/workaround

```
// implemented via vue extends
const FixedFixedHeader = {
  extends: FixedHeader,
  mounted () {
    this.lastScrollTop = this.getScrollTop()
    this.check = () => {
      const { threshold, hideScrollUp } = this
      const currentScrollPos = this.getScrollTop()

       // testing for threshold after checking hideScrollUp was the real issue - otherwise its in 
       // `!hideScrollUp` which sets isFixed:true always

      const isFixed =
          currentScrollPos >= this.lastScrollTop
            ? currentScrollPos > threshold
            : (hideScrollUp ? false : currentScrollPos > threshold)
      this.lastScrollTop = currentScrollPos

      // CHANGE 1: only emit change if there was a change
      if (this.isFixed === isFixed) {  
        return
      }

      this.isFixed = isFixed
      this.$emit('change', this.isFixed)
      // CHANGE 2: drop $forceUpdate
      // this.$forceUpdate() 
    }
    this.registerEvent()
  },
  computed: {
    // CHANGE 3: create {passive:true} for browser that support it
    scrollEventOptions () {
      let passiveSupported = false

      try {
        const options = {
          get passive () { // This function will be called when the browser
            //   attempts to access the passive property.
            passiveSupported = true
            return false
          }
        }
        window.addEventListener('test', null, options)
        window.removeEventListener('test', null, options)
      } catch (err) {
        passiveSupported = false
      }
      return passiveSupported ? { passive: true } : false
    }
  },
  methods: {
    registerEvent () {
      // CHANGE 4: add {passive:true} for browser that support it, or false
      window.addEventListener('scroll', this.check, this.scrollEventOptions) 
    },
    removeEvent () {
      // CHANGE 4: add {passive:true} for browser that support it, or false
      window.removeEventListener('scroll', this.check, this.scrollEventOptions)
    }
  }
}
```

**Comment by Ap0gee** [comment]
Well done @birdspider! This solution has solved this issue for me. Thank you.

**Comment by butaminas** [comment]
This is also a fix for: https://github.com/potato4d/vue-fixed-header/issues/226

Great work @birdspider!

**Comment by birdspider** [comment]
just to make it clear, the changes to `this.change` are the actual fix

the changes regarding passive `scroll` events are just a bonus, but I wanted to provide a full testable example/component - and that was what I had at hand

**Comment by potato4d** [comment]
@birdspider 
May I have a Pull Request?

**Comment by Blair2004** [comment]
So bad the fix hasn't been implemented so far by the author.

**Comment by birdspider** [comment]
@potato4d I'll do a PR if I find the time - this week

probably 2 parts - the fix itself and if you want it - the passive scroll

**Comment by birdspider** [comment]
regarding the passive scroll "handling" - seems to be a no-op 

(I don't know why there was a warning in chrome regarding this. it is not happening anymore)

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener says:

> According to the specification, the default value for the passive option is always false. However, this introduces the potential for event listeners handling certain touch events (among others) to block the browser's main thread while it is attempting to handle scrolling, resulting in possibly enormous reduction in performance during scroll handling.

> To prevent this problem, some browsers (specifically, Chrome and Firefox) have changed the **default value** of the passive option to **true** for the **touchstart** and **touchmove** events on the document-level nodes **Window, Document, and Document.body**. This prevents the event listener from being called, so it can't block page rendering while the user is scrolling.

> **You don't need to worry about the value of passive for the basic scroll event**. Since it can't be canceled, event listeners can't block page rendering anyway.

---

Therefore I will **not** provide a PR for `scroll:passive`
