### ISSUE TITLE
Doesn't work in IE Edge

### ISSUE THREAD

**Issue by CookiesEater** [potato4d/vue-fixed-header#5]
Hi!
Scrolling does not work on IE Edge with example https://potato4d.github.io/vue-fixed-header/
Tested in Microsoft Edge 41.16299.248.0
In IE11 works fine

If in component manualy change tag from 'html' to 'body' it works fine (with 'html' scrollTop always return 0)

**Comment by potato4d** [comment]
@CookiesEater 
Oh, thanks.
I do not have Windows now, but I will check as soon as possible.
